#!/bin/bash

mount /dev/disk/by-label/archlinux /mnt
mkdir /mnt/boot
mount -o umask=077 /dev/disk/by-label/SYSTEM /mnt/boot

read -p "debug"

pacstrap -K /mnt base linux linux-firmware amd-ucode nvidia networkmanager plasma-desktop sddm

read -p "debug"

genfstab -U /mnt >> /mnt/etc/fstab
ln -sf /mnt/usr/share/zoneinfo/Europe/Berlin /mnt/etc/localtime
echo "en_US.UTF-8 UTF-8" > /mnt/etc/locale.gen
arch-chroot /mnt locale-gen
echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf
echo linux > /mnt/etc/hostname
echo -ne "127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\tlinux.localdomain linux" > /mnt/etc/hosts
arch-chroot /mnt systemctl enable NetworkManager.service
arch-chroot /mnt passwd
arch-chroot /mnt useradd -m -G wheel pino
arch-chroot /mnt passwd pino
arch-chroot /mnt bootctl install
echo -ne "default windows.conf\ntimeout menu-force\neditor false\nauto-entries false" > /mnt/boot/loader/loader.conf
echo -ne "title Arch Linux\nlinux /vmlinuz-linux\ninitrd /amd-ucode.img\ninitrd /initramfs-linux.img\noptions root=/dev/nvme0n1p3 rw nvidia_drm.modeset=1" > /mnt/boot/loader/entries/archlinux.conf
echo -ne "title Windows\nefi /EFI/Microsoft/Boot/bootmgfw.efi" > /mnt/boot/loader/entries/windows.conf

read -p "debug"